openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths: {}

components:
  schemas:
    Response:
      type: object
      properties:
        id:
          type: UUID
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        employee:
          type: array
          items:
            $ref: "#/components/schemas/Employee"
    Employee:
      type: object
      properties:
        id:
          type: UUID
        login:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        lastActive:
          type: string
          format: date-time
        passport:
          $ref: '#/components/schemas/Passport'
    Passport:
      type: object
      properties:
        series:
          type: number
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        number:
          type: number
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        birthDate:
          type: string
          format: date
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        sex:
          $ref: '#/components/schemas/Sex'
        placeOfIssue:
          type: string
    Sex:
      type: string
      enum:
        - MALE
        - FEMALE
      x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"