openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths: {}

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        login:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        post:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        series:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        number:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
    Order:
      type: object
      properties:
        bisId:
          type: array
          items:
            type: string
        id:
          type: string
        type:
          type: string
          x-field-extra-annotation: "@ru.evg.mask_logback.maskUtil.finder.MaskingField"
        user:
          items:
            $ref: "#/components/schemas/User"
    OrderResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"